name: Python Build

# Thiết lập khi nào action này sẽ được kích hoạt
on:
  push:         # Khi có push code vào repository
    branches:
      - master  # Chạy khi push vào nhánh master
  pull_request: # Khi tạo pull request trên nhánh master

# Định nghĩa các job sẽ chạy
jobs:
  build:

    # Thiết lập môi trường chạy job này
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Bước 2: Thiết lập phiên bản Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Bạn có thể đặt phiên bản Python cần thiết

    # Bước 3: Cài đặt các dependency (nếu có)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Nếu bạn có file requirements.txt thì thêm dòng sau:
        # pip install -r requirements.txt

    # Bước 4: Chạy file Subset.py
    - name: Run Python script
      run: |
        python Python/p78_Subsets/Subset.py
